# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edde1d9fde073b325de104d57a28f5b4b0be4c5d2b9be26d17e93c383535080a0ccd56d15b3d01ee8bf52fe832825fee962fe3f176f3977aa000d3cad7d0811a

test:
  secret_key_base: 8027703686475a69f4537accee88c84c62d1a8e396c2977cf9b51db4a6392219bbb915f6ec71c88f3b855ffdd1dcf7cf830bb1e0b85c2b1649a600c7ed24cce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
